Fix a failing test caused by a missing request linked to the controller
Fixed a test failure like the one below. The test still fails due to a different issue, but this commits the fix for one resolved problem.

```
  1) Gon::Global with jbuilder and rabl works fine with rabl
     Failure/Error: output = RablRails::Library.instance.get_rendered_template(source, view_context)

     NoMethodError:
       undefined method 'filtered_parameters' for nil
     # ./lib/gon/rabl.rb:60:in 'Gon::Rabl.parse_with_rabl_rails'
     # ./lib/gon/rabl.rb:38:in 'Gon::Rabl.parse_rabl'
     # ./lib/gon/rabl.rb:24:in 'Gon::Rabl.handler'
     # ./lib/gon/global.rb:20:in 'Gon::Global.rabl'
     # ./spec/gon/global_spec.rb:133:in 'block (3 levels) in <top (required)>'
```